### ISSUE TITLE
Call M3S with Python

### ISSUE THREAD

**Issue by bearinsuke** [ucascnic/CudaOT#4]
Hi, 

Is there any example for M3S algorithm on Python? If not, how can I call those functions from your cpp files?

**Comment by ucascnic** [comment]
Happy new year! A simple python example could be found in:

https://github.com/ucascnic/CudaOT/blob/main/pythonExample/sparseOT/sparse_transport.py

The function log_sinkhorn_sparse implements a stable and simple M3S algo.

**Comment by bearinsuke** [comment]
Thanks for your reply. Happy new year!
